# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - pipe: snyk/snyk-scan:0.2.0
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: "npm"
              DONT_BREAK_BUILD: "true"
              MONITOR: "true"
              EXTRA_ARGS: "--project-name=goof-bitbucket-pipelines --remote-repo-url=goof-bitbucket-pipelines"
