version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Secret Manager 
    SNYK_TOKEN: "SNYK_TOKEN"
    SLACK_TOKEN: "SLACK_API_TOKEN"

phases:
  install:
    commands:
      - npm install -g snyk 
      - npm install -g snyk-to-html 
      - npm install -g html-pdf
      - npm link html-pdf && npm link phantomjs-prebuilt
  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - snyk test --json | snyk-to-html -o results.html
      - html-pdf results.html results.pdf
      - >
        python -c "import os; import requests; url = 'https://slack.com/api/files.upload'; my_file = {'file' : ('results.pdf', open('results.pdf', 'rb'), 'pdf')}; payload = {'filename':'results.pdf', 'token': os.getenv('SLACK_TOKEN'), 'channels': ['#notification-aws-codebuild']}; response = requests.post(url, params=payload, files=my_file); print(response.text)"
        
