version: 0.2

env:
  parameter-store:
    # Secure string in AWS Secret Manager 
    SNYK_TOKEN: "SNYK_TOKEN"
    SNYK_ORG: "SNYK_ORG"

phases:
  install:
    commands:
      - npm install -g snyk 
  build:
    commands:
      - npm install
      - npm test  
      - snyk test --org="${SNYK_ORG}"

