
version: 0.2
env:
  parameter-store:
    # Requires that you have a secure string in AWS Secret Manager 
    SNYK_TOKEN: "SNYK_TOKEN"
    SNYK_ORG_ID: "SNYK_ORG_ID"
    JIRA_PROJECT_ID: "JIRA_PROJECT_ID"

phases:
  install:
    commands:
      - npm install -g snyk 
      - cd /tmp && wget https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/0.4.0/snyk-jira-sync-linux
      - chmod -R +x snyk-jira-sync-linux && mv snyk-jira-sync-linux /codebuild/user/bin/ && cd -
  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - snyk-jira-sync-linux -orgID="${SNYK_ORG_ID}" -token="${SNYK_TOKEN}" -jiraProjectID="${JIRA_PROJECT_ID}" -severity=high
variables:
    SLACK_POST_SCRIPT: |
      import os
      import requests
      url = 'https://slack.com/api/files.upload'
      my_file = {'file' : ('results.pdf', open('results.pdf', 'rb'), 'pdf')}
      payload = {'filename':'results.pdf', 'token': os.getenv('SLACK_TOKEN'), 'channels': ['#notification-aws-codebuild']}
      response = requests.post(url, params=payload, files=my_file)
      print(response.text)
phases:
  install:
    commands:
      - npm install -g snyk 
      - npm install -g snyk-to-html
      - apt-get update && apt-get install -y wget xfonts-75dpi
      - cd /tmp && wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
      - dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb || true
      - apt-get -f install -y && cd -
  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - snyk test --json | snyk-to-html -o results.html
      - wkhtmltopdf results.html results.pdf
      - python -c "${SLACK_POST_SCRIPT}"
