version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Secret Manager 
    SNYK_TOKEN: "SNYK_TOKEN"
    SNYK_ORG_ID: "SNYK_ORG_ID"
    JIRA_PROJECT_ID: "JIRA_PROJECT_ID"

phases:
  install:
    commands:
      - npm install -g snyk 
      - curl -Lo ./snyk_jira_sync https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/0.4.0/snyk-jira-sync-linux
      - chmod -R +x ./snyk_jira_sync      
  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - ./snyk-jira-sync-linux -orgID="${SNYK_ORG_ID}" -token="${SNYK_TOKEN}" -jiraProjectID="${JIRA_PROJECT_ID}" -severity=high
