version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Secret Manager 
    SNYK_TOKEN: "SnykCodeBuildToken"

phases:
  install:
    commands:
      - npm install -g snyk
      - curl -Lo ./snyk-jira-sync "https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/0.4.0/snyk-jira-sync-linux"
      - chmod -R +x ./snyk_jira-sync

  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - ./snyk-jira-sync. -orgID="$baseline-org" -projectID="$baseline-proj" -token="$SnykCodeBuildToken" -jiraProjectID=10002  
   

#artifacts:
#  files:
#    - '**/*'
#  name: snyk-result
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths
