version: "2.1"
orbs:
  snyk: snyk/snyk@1.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - snyk/scan:
        fail-on-issues: false
        monitor-on-build: true
        project: "${}/${}-app"
        severity-threshold: high
        token-variable: SNYK_TOKEN
workflows: null
