version: "2"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
    depends_on:
      - goof-mongo
  goof-mongo:
    container_name: goof-mongo
    image: mongo:3
    platform: linux/amd64  # Add this line to specify the platform (On M2 Mac)
    ports:
      - "27017:27017"
  goof-mysql:   # Corrected the typo here
    container_name: goof-mysql   # And here
    image: mysql:5
    platform: linux/amd64  # Add this line to specify the platform (On M2 Mac)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"
