version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/goof # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-snyk
          command: 'sudo npm install -g snyk'     
      - run: # run npm test
          name: snyk-help
          command: snyk --help
      - run: # run snyk auth
          name: snyk auth
          command: snyk auth $SNYK_TOKEN
      - run: # run snyk test
          name: snyk test
          command: snyk test