version: 2.1

# Define environment variables
environment:
  # Existing line referencing environment variable SNYK_TOKEN (no need to remove)

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn install
      - snyk/install
      - run: snyk code test --token $SNYK_TOKEN  # Access token from environment variable

workflows:
  build-snyk:
    jobs:
      - snyk-scan
