---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-goof
  labels:
    app: nodejs-goof
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-goof
    