name: Snyk Code PR Diff Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  snyk-pipeline:
    runs-on: ubuntu-latest
    name: Snyk Code PR Diff Scan
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
    steps:
      # Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2

      # Download and install Snyk
      - name: Download and install Snyk
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      # Authenticate Snyk
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      # Run Snyk Code on PR branch
      - name: Run Snyk Code on PR branch
        run: snyk code test --json-file-output=${{ github.workspace }}/snyk_code_pr.json || true
        continue-on-error: true

      # Upload Snyk Code results from PR scan
      - name: Upload Snyk Code results from PR scan
        if: success() && steps.snyk-pipeline.outputs.exit-code != 0
        uses: actions/upload-artifact@v2
        with:
          name: snyk_code_pr
          path: ${{ github.workspace }}/snyk_code_pr.json

      # Download Snyk Code results from main branch
      - name: Download Snyk Code results from main branch
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: snyk_code_baseline

      # Check if new issues have been introduced via the PR
      - name: Check for new issues introduced via the PR
        if: always()
        run: |
          chmod +x ${{ github.workspace }}/.github/snyk-pr-diff-amd64-linux
          ${{ github.workspace }}/.github/snyk-pr-diff-amd64-linux code ${{ github.workspace }}/snyk_code_baseline.json ${{ github.workspace }}/snyk_code_pr.json
