name: "CodeQL"

on: push

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest 

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    # Specify the container in which actions will run
    container:
      image: mcr.microsoft.com/cstsectools/codeql-container

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Build
      run: |
        apt-get update -qq && apt-get install -y build-essential nodejs
        npm install
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
