name: "Snyk Scan"

on:
  push:
    branches:
      - '*'

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --report --project-name="GH_ACTION_CI" --severity-threshold=high 
        continue-on-error: true
      # Run Snyk OS
      - name: Run Snyk OS
        run: |
          snyk monitor --project-name="GH_ACTION_CI" --severity-threshold=high 
        continue-on-error: true

