name: Snyk Scan Master
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: NPM Install
        run: npm install
      - name: Install Snyk
        run: sudo npm install -g snyk
      - name: ECHO TEST
        run: echo "Test"
      - name: ECHO "$SUPER_SECRET"
        run: echo "$SUPER_SECRET"
      - name: Snyk Authenticate
        run: snyk auth "$SUPER_SECRET"
      - name: Snyk Test
        run: snyk test
