name: Snyk Scan Master
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Install
        run: npm install
      - name: Install Snyk
        run: sudo npm install -g snyk
      - name: ECHO ENV VAR
        run: echo env.SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Authenticate
        run: snyk auth env.SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Test
        run: snyk test
