name: Open Source Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  open-source-test:
    uses: somerset-inc/somerset-workflows/.github/workflows/snyk-opensource-wrapper.yml@main
    secrets: inherit