name: Example workflow using Snyk
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk.json
          

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          cat snyk.json | snyk-to-html -o result.html
          mkdir downloads
          pwd
          ls -al
          cp -v /home/runner/work/goof/goof/*.html /home/runner/work/goof/goof/downloads
      - name: Run Snyk test 
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: downloads
